omp/apps/models.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# Created by huangtao@oraro
from omp import db


class Apps(db.Model):
    """
    应用表
    """
    __tablename__ = 'omp_apps'

    id = db.Column(db.Integer, primary_key=True)
    # app名称
    name = db.Column(db.String(200), unique=True)
    desc = db.Column(db.String(200))

omp/hours/models.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# Created by huangtao@oraro
from omp import db


class ManHour(db.Model):
    """
    工时统计
    """
    __tablename__ = 'omp_hours'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('omp_user.id'))
    user = db.relationship('User', backref=db.backref('omp_hours_user', order_by=id))
    app_id = db.Column(db.Integer, db.ForeignKey('omp_apps.id'))
    app = db.relationship('Apps', backref=db.backref('omp_hours_apps', order_by=id))
    hour = db.Column(db.Float)
    day = db.Column(db.Date)

omp/__init__.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# Created by huangtao@oraro
from flask import Flask
from flask_mail import Mail
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

from config import config

mail = Mail()
db = SQLAlchemy()
# 这样就使未登录的直接跳转到登录界面
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    mail.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    # 注册每个APP view对应的蓝本
    # 处理根url
    from omp.main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    # 登录
    from omp.auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')
    # 管理
    from omp.manager import manager as manager_blueprint
    app.register_blueprint(manager_blueprint, url_prefix='/manager')
    # app
    from omp.apps import apps as apps_blueprint
    app.register_blueprint(apps_blueprint, url_prefix='/apps')
    # 填写工时
    from omp.hours import hours as hours_blueprint
    app.register_blueprint(hours_blueprint, url_prefix='/hours')
    # 工时统计
    from omp.reports import reports as reports_blueprint
    app.register_blueprint(reports_blueprint, url_prefix='/reports')
    return app

omp/apps/__init__.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# Created by huangtao@oraro
from flask import Blueprint

apps = Blueprint('apps', __name__)
from . import views

omp/apps/views.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# Created by huangtao@oraro
from flask import flash, session, request, url_for, redirect, render_template
from flask_login import login_required, current_user
from . import apps
from .models import Apps
from omp import db


@apps.route('/all_apps')
@login_required
def all_apps():
    all_apps = Apps.query.all()
    return render_template('apps/all_apps.html', all_apps=all_apps)


@apps.route('/add_apps', methods=["GET", "POST"])
@login_required
def add_apps():
    if request.method == "POST":
        app_name = request.form.get('app_name')
        old_app = Apps.query.filter(Apps.name == app_name).first()
        if old_app:
            flash("此App已经存在!!", "warning")
            return redirect(url_for("apps.all_apps"))
        desc = request.form.get('desc')
        app = Apps()
        app.name = app_name
        app.desc = desc
        db.session.add(app)
        db.session.commit()
        flash("App添加成功!!", "success")
        return redirect(url_for("apps.all_apps"))

    return render_template('apps/app_add.html', app=None)

omp/hours/__init__.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# Created by huangtao@oraro

# 注册blueprint
from flask import Blueprint


hours = Blueprint('hours', __name__)
from . import views

omp/hours/views.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# Created by huangtao@oraro
from omp import db
from flask import session, render_template, url_for, current_app, request, flash, redirect
from flask_login import login_required, current_user
from . import hours
from omp.apps.models import Apps
from .models import ManHour


@hours.route('/add_hours', methods=['GET', 'POST'])
@login_required
def add_hours():
    """
    录入工时
    :return:
    """
    apps = Apps.query.all()
    if request.method == "POST":
        # 记录的时间
        day = request.form.get('day')
        # 查询每一条记录
        for key in request.form.keys():
            if key.startswith('app_id'):
                index = key.split('_')[-1]
                # 所属项目
                app_id = request.form.get('app_id_' + index)
                # 消耗时间
                hour = request.form.get('spend_hour_' + index)
                # 查询是否已经有此项目记录,如果有就更新数据
                man_hour = ManHour.query.filter(db.and_(ManHour.app_id == app_id,ManHour.user_id == current_user.id,ManHour.day == day)).first()
                if not man_hour:
                    man_hour = ManHour()
                man_hour.app_id = app_id
                man_hour.user_id = current_user.id
                man_hour.day = day
                man_hour.hour = hour
                db.session.add(man_hour)
                db.session.commit()
        flash('工时录入成功', 'success')
        return redirect(url_for('hours.my_hours'))
    return render_template('hours/add_hours.html', apps=apps)


@hours.route('/my_hours')
@login_required
def my_hours():
    """
    查看自己的工时
    :return:
    """
    my_hours = ManHour.query.filter(ManHour.user_id == current_user.id).order_by(ManHour.day.desc()).all()
    return render_template('hours/my_hours.html', hours=my_hours)

omp/main/__init__.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# Created by mark.huang on 2018/6/27.
from flask import Blueprint

main = Blueprint('', __name__)
from . import views

omp/main/views.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# Created by mark.huang on 2018/6/27.
from . import main
from flask_login import login_required, current_user
from flask import redirect, url_for, render_template


@main.route('/')
@login_required
def mains():
    return redirect(url_for(current_user.role.index_page))


@main.app_errorhandler(404)
def page_not_found(e):
    return render_template('main/404.html'), 404


@main.app_errorhandler(502)
def page_not_found(e):
    return render_template('main/error.html', error='502'), 500


@main.app_errorhandler(500)
def page_not_found(e):
    return render_template('main/error.html', error='500'), 500

omp/manager/__init__.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# Created by mark.huang on 2018/7/2.
from flask import Blueprint

manager = Blueprint('manager', __name__)
from . import views

omp/manager/views.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# Created by mark.huang on 2018/7/2.
from . import manager
from flask_login import login_required, current_user
from flask import redirect, url_for, render_template, request, flash, session
from omp.auth.models import SystemParameter, Menu, Role, User, Organization
from omp import db
from omp.auth.views import create_menu
from ldap3 import Server, Connection, ALL
from config import Config


@manager.route('/accounts_manage')
@login_required
def accounts_manage():
    """
    账号管理
    :return:
    """
    # 查询所有用户
    users = User.query.all()
    return render_template('manager/accounts.html', users=users)


@manager.route('/show_menus')
@login_required
def show_menus():
    """
    展示菜单
    :return:
    """
    menus = Menu.query.order_by(Menu.menu_order).all()
    parents = []
    result = {}
    for menu in menus:
        if menu.parent and menu.parent in result.keys():
            result[menu.parent].append(menu)
        elif menu.parent:
            result.update({menu.parent: [menu]})
            if not menu.parent in parents:
                parents.append(menu.parent)
        else:
            if not menu in parents:
                parents.append(menu)
            result.update({menu.parent: []})

    parents = sorted(parents, key=get_order)
    return render_template('manager/system_menu_page.html', parents=parents, menus=result)


@manager.route('/add_menu', methods=['GET', 'POST'])
@login_required
def add_menu():
    """
    添加菜单
    :return:
    """
    if request.method == 'POST':
        menu_name = request.form['menu_name']
        menu_url = request.form['menu_url']
        active = True if request.form.get('activate', 'off') == 'on' else False
        menu_icon = request.form['menu_icon']
        menu_desc = request.form['menu_desc']
        menu_order = request.form['menu_order']
        parent_id = request.form['parent_id']
        is_parent = False if parent_id else True
        new_menu = Menu()
        new_menu.menu_name = menu_name
        new_menu.menu_url = menu_url
        new_menu.active = active
        new_menu.menu_icon = menu_icon
        new_menu.menu_desc = menu_desc
        new_menu.menu_order = menu_order
        if parent_id:
            new_menu.parent_id = parent_id
        new_menu.is_parent = is_parent
        db.session.add(new_menu)
        db.session.commit()
        flash('菜单添加成功', 'success')
        return redirect(url_for('manager.show_menus'))
    else:
        menu_icons = SystemParameter.query.filter(SystemParameter.key == 'menu_icons').first().value.split(',')
        parent_menus = Menu.query.filter(Menu.is_parent).all()
        return render_template('manager/add_menu.html', menu=None, menu_icons=menu_icons, parent_menus=parent_menus)


@manager.route('/edit_menu/<int:menu_id>', methods=['GET', 'POST'])
@login_required
def edit_menu(menu_id):
    """
    修改菜单
    :param menu_id:
    :return:
    """
    menu = Menu.query.filter(Menu.id == menu_id).first()
    if request.method == 'POST':
        menu_name = request.form['menu_name']
        menu_url = request.form['menu_url']
        active = True if request.form.get('activate', 'off') == 'on' else False
        menu_icon = request.form['menu_icon']
        menu_desc = request.form['menu_desc']
        menu_order = request.form['menu_order']
        parent_id = request.form['parent_id']
        is_parent = False if parent_id else True
        if menu:
            menu.menu_name = menu_name
            menu.menu_url = menu_url
            menu.active = active
            menu.menu_icon = menu_icon
            menu.menu_desc = menu_desc
            menu.menu_order = menu_order
            if parent_id:
                menu.parent_id = parent_id
            menu.is_parent = is_parent
            db.session.add(menu)
            db.session.commit()
            flash('菜单修改成功', 'success')
        else:

            new_menu = Menu()
            new_menu.menu_name = menu_name
            new_menu.menu_url = menu_url
            new_menu.active = active
            new_menu.menu_icon = menu_icon
            new_menu.menu_desc = menu_desc
            new_menu.menu_order = menu_order
            if parent_id:
                new_menu.parent_id = parent_id
            new_menu.is_parent = is_parent
            db.session.add(new_menu)
            db.session.commit()
            flash('菜单添加成功', 'success')
        role = current_user.role
        if role and role.menu:
            menu_ids = [menu_id for menu_id in role.menu.split(',') if id]
            menus = [menu for menu in Menu.query.filter(
                db.and_(Menu.active == True,
                        Menu.id.in_(menu_ids))).order_by(Menu.menu_order).all()]
        else:
            menus = []
        session['menu'] = create_menu(menus)
        return redirect(url_for('manager.show_menus'))
    else:
        menu_icons = SystemParameter.query.filter(SystemParameter.key == 'menu_icons').first().value.split(',')
        parent_menus = Menu.query.filter(Menu.is_parent).all()
        return render_template('manager/add_menu.html', menu=menu, menu_icons=menu_icons, parent_menus=parent_menus)


def get_order(menu):
    if menu:
        return menu.menu_order
    else:
        return 0


@manager.route('/_menu_activate')
@login_required
def set_menu_activate():
    menu_id = request.args.get('id', 0, type=int)
    activate = request.args.get('activate')
    if activate == 'Enable':
        db.session.execute('UPDATE omp_menu SET active=1 WHERE id =%s or parent_id=%s' % (menu_id, menu_id))
    elif activate == 'Disable':
        db.session.execute('UPDATE omp_menu SET active=0 WHERE id =%s or parent_id=%s' % (menu_id, menu_id))
    db.session.commit()

    return '{"result": true}'


@manager.route('/role_manage')
@login_required
def role_manage():
    roles = Role.query.all()
    return render_template('manager/role_manage.html', roles=roles)


@manager.route('/add_role', methods=['GET', 'POST'])
@login_required
def add_role():
    if request.method == 'POST':
        role_name = request.form['rolename']
        index_page = request.form['indexpage']
        role = Role()
        role.name = role_name
        role.index_page = index_page
        old_role = Role.query.filter(Role.name == role_name).first()
        if old_role:
            flash('角色已经存在!', 'warning')
        else:
            db.session.add(role)
            db.session.commit()
            flash('角色添加成功!', 'success')
            return redirect(url_for('manager.role_manage'))
    return render_template('manager/role_add.html')


@manager.route('/edit_role/<int:role_id>', methods=['GET', 'POST'])
@login_required
def edit_role(role_id):
    role = Role.query.filter(Role.id == role_id).first()
    if request.method == 'POST':
        all_id = [str(menu_id) for menu_id in request.form.getlist('role_menu') if menu_id]

        if all_id:
            query_sql = "SELECT DISTINCT  parent_id FROM omp_menu WHERE id IN(%s)" % ','.join(all_id)

            for row in db.engine.execute(query_sql):
                if row[0] != 'None' and row[0] != None:
                    all_id.append(str(row[0]))

            role.menu = ','.join(list(set(all_id)))
        else:
            role.menu = ''

        role.name = request.form['name']
        role.index_page = request.form['index_page']

        db.session.add(role)
        db.session.commit()

        user_ids = request.form.getlist('role_member')
        member = User.query.filter_by(role_id=role.id).all()
        for user in member:
            if user.id in user_ids:
                user_ids.remove(user.id)
            else:
                user.role = None
                db.session.add(user)

        users = User.query.filter(User.id.in_(user_ids))
        for user in users:
            user.role = role
            db.session.add(user)
        db.session.commit()

        flash('修改成功', 'success')
        session['index_page'] = request.form['index_page']
        role = current_user.role
        if role and role.menu:
            menu_ids = [menu_id for menu_id in role.menu.split(',') if id]
            menus = [menu for menu in Menu.query.filter(
                db.and_(Menu.active == True,
                        Menu.id.in_(menu_ids))).order_by(Menu.menu_order).all()]
        else:
            menus = []
        session['menu'] = create_menu(menus)
        return redirect(url_for('manager.role_manage'))
    role_menu = [int(id) for id in role.menu.split(',') if id] if role.menu else []
    menus = Menu.query.all()
    users = User.query.all()
    return render_template('manager/role_edit.html', role=role, role_menu=role_menu, menus=menus, users=users)


@manager.route('/add_user', methods=['POST', 'GET'])
@login_required
def add_user():
    if request.method == 'POST':
        cn = request.form.get('cn')
        mail = request.form.get('mail')
        uid = request.form.get('uid')
        try:
            # 定义ldap服务器
            s = Server(Config.LDAP_HOST,
                       get_info=ALL)
            # 定义连接
            c = Connection(s, user=Config.LDAP_ADMIN_USER, password=Config.LDAP_PASSWD, auto_bind=True)
            # 添加用户
            c.add('cn=%s,%s' % (cn, Config.LDAP_SEARCH_BASE),
                  attributes={'objectClass': ['inetOrgPerson', 'top'], 'mail': mail, 'userPassword': '123456', 'sn': cn,
                              'uid': uid})
            c.unbind()
            flash('添加成功!', 'success')
        except Exception as e:
            flash('添加失败:%s' % str(e), 'warning')
        return redirect(url_for('manager.add_user'))
    return render_template('manager/user_add.html')


@manager.route('/system_para')
@login_required
def system_para():
    paras = SystemParameter.query.all()
    return render_template('manager/system_para.html', paras=paras)


@manager.route('/edit_para/<int:para_id>', methods=['POST', 'GET'])
@login_required
def edit_para(para_id):

omp/reports/__init__.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# Created by huangtao@oraro
from flask import Blueprint

reports = Blueprint('reports', __name__)
from .views import *

omp/utils/__init__.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# Created by huangtao@oraro

omp/templates/apps/all_apps.html
{% extends "base.html" %}
{% block title %}
    通用配置
{% endblock %}
{% block head %}
    {{ super() }}
    <link href="{{ url_for('static', filename='assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css') }}"
          rel="stylesheet" type="text/css"/>
    <link href="{{ url_for('static', filename='assets/global/plugins/select2/select2.css') }}" rel="stylesheet"
          type="text/css"/>
{% endblock %}
{% block page_title %}
    <h1>通用配置
        <small>所有应用</small>
    </h1>
{% endblock %}
{% block page_content %}
    <!-- BEGIN CONTENT -->
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet box grey-cascade">
                <div class="portlet-title">
                    <div class="caption">所有应用</div>
                </div>
                <div class="portlet-body">

                    <div class="table-toolbar">
                        {% if session['user'].role in ['admin'] %}
                            <div class="row">
                                <div class="col-sm-1">
                                    <div class="btn-group">
                                        <a id="add_user" class="btn green"
                                           href="{{ url_for('apps.add_apps') }}">
                                            新增应用
                                        </a>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                    <table class="table table-striped table-bordered table-hover" id="apps_table">
                        <thead>
                        <tr>
                            <th width="20px;">No</th>
                            <th>应用名</th>
                            <th>描述</th>
                        </tr>
                        </thead>
                        {% for app in all_apps %}
                                <tr data="{{ app.id }}">
                                    <td>{{ loop.index }}</td>
                                    <td>{{ app.name }}</td>
                                    <td>{{ app.desc }}</td>
                                </tr>
                        {% endfor %}
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
    <!-- END PAGE CONTENT-->
{% endblock %}
{% block page_script %}
    <script src="{{ url_for('static', filename='assets/global/plugins/datatables/media/js/jquery.dataTables.min.js') }}"
            type="text/javascript"></script>
    <script src="{{ url_for('static', filename='assets/global/plugins/datatables/extensions/TableTools/js/dataTables.tableTools.min.js') }}"
            type="text/javascript"></script>
    <script src="{{ url_for('static', filename='assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js') }}"
            type="text/javascript"></script>
    <script src="{{ url_for('static', filename='assets/global/plugins/bootbox/bootbox.min.js') }}"
            type="text/javascript"></script>
    <script type="text/javascript">
        $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
    </script>
{% endblock %}

omp/templates/apps/app_add.html
{% extends "base.html" %}
{% block title %}
    App增加
{% endblock %}
{% block head %}
    {{ super() }}
    <link href="{{ url_for('static', filename='assets/global/plugins/select2/select2.css') }}" rel="stylesheet"
          type="text/css"/>
{% endblock %}
{% block page_title %}
    <h1>App管理
        <small>App增加</small>
    </h1>
{% endblock %}
{% block page_content %}
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN PORTLET-->
            <div class="portlet box blue-ebonyclay">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-gift"></i>
                    </div>
                </div>
                <div class="portlet-body form">
                    <form action="" id="app_add_form" class="horizontal-form" method='POST'
                          onsubmit="show_mask();">
                        <div class="form-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <div class="form-group">
                                        <label class="control-label">App名称</label>
                                        <input type="text" id="app_name" name="app_name" class="form-control"
                                               value="{{ app.name }}" required/>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="control-label">描述</label>
                                        <textarea id="desc" name="desc" class="form-control"
                                                  rows="3" required>{{ app.desc }}</textarea>
                                    </div>
                                </div>

                            </div>
                        </div>
                        {% if session['user']['role'] == 'admin' %}
                            <div class="form-actions right" id="submit_btn">
                        {% else %}
                            <div class="form-actions right" id="submit_btn" hidden>
                        {% endif %}
                        <div class="row">
                            <div class="col-md-offset-5 col-md-7">
                                <button type="submit" class="btn purple"><i class="fa fa-check"></i>提交
                                </button>
                                <a type="button" class="btn default" href="{{ url_for('apps.all_apps') }}">取消</a>
                            </div>
                        </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- END PORTLET-->
    </div>
{% endblock %}
{% block page_script %}
    <script src="{{ url_for('static', filename='assets/global/plugins/select2/select2.min.js') }}"></script>
{% endblock %}